// 按页加载文章的 Metadata
export const GET_ARTICLE_METADATA_BY_PAGE = 'get_article_metadata_by_page';

export const GET_ARTICLE_METADATA_FIRST_PAGE = 'GET_ARTICLE_METADATA_FIRST_PAGE'
export const GET_ARTICLE_METADATA_NEXT_PAGE = 'GET_ARTICLE_METADATA_NEXT_PAGE'
export const GET_ARTICLE_METADATA_PREVIOUS_PAGE = 'GET_ARTICLE_METADATA_PREVIOUS_PAGE'
